/**
 * The creators, pinned to their bytes.
 *
 * WHY THIS EXISTS, AND WHY IT IS DELIBERATELY BRITTLE. Every other fidelity
 * test in this repo is about the EDITOR: open a real file, change one cell,
 * prove nothing else moved. Nothing was about the CREATOR — the code that makes
 * an .xlsx or .docx from nothing, which is every template in the gallery, every
 * seeded document, and the workbook a .csv becomes when somebody opens it.
 *
 * That gap had teeth. Moving the creator into @rutba/ooxml, a change with no
 * behaviour in it at all, introduced a one-column shift into every generated
 * workbook: `colName` was rewritten as `indexToCol(n + 1)` on the assumption
 * that the shared function counted columns from one. It counted from zero. The
 * files still opened. They just had an empty column A, every value one place to
 * the right — and 477 tests passed. What caught it was hashing the old
 * implementation's output against the new one by hand, once, and that is not a
 * thing anybody will remember to do next time.
 *
 * So the digests below are the gate. A change to generated bytes should be
 * DELIBERATE, and this test failing is how it becomes deliberate: update the
 * digest in the same commit that changes the output, and say in the message
 * what moved and why. A creator whose bytes can drift unnoticed is a creator
 * that can quietly corrupt a customer's file.
 *
 * The structural assertions underneath are what make a failed digest
 * diagnosable. A hash tells you something changed; `A1` tells you what.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import {
  buildXlsx, buildDocx, buildLetterDocx,
  readWorkbook, readSheetValues, readSheetNames, readDefinedNames,
  colName, cellRef, OoxmlPackage,
} from '@rutba/ooxml';

const sha = (buf) => createHash('sha256').update(buf).digest('hex').slice(0, 16);

/** One spec per shape, so a failure names the feature that moved. */
const SHAPES = {
  plain: () => buildXlsx({
    sheets: [{ name: 'Data', rows: [['a', 'b&<>"é'], [1, 2]] }],
    definedNames: [{ name: 'Rng', ref: 'Data!$A$1:$B$2' }],
  }),
  styled: () => buildXlsx({
    sheets: [{ name: 'S', rows: [['Head'], [1]], styles: { A1: { bold: true, fill: 'FFEEEEEE' } } }],
  }),
  multiSheet: () => buildXlsx({
    sheets: [{ name: 'One', rows: [[1]] }, { name: 'Two', rows: [[2]] }],
  }),
  formula: () => buildXlsx({ sheets: [{ name: 'F', rows: [[1, 2, '=A1+B1']] }] }),
  charted: () => buildXlsx({
    sheets: [{
      name: 'C',
      rows: [['Jan', 'Feb'], [10, 20]],
      drawings: [{
        kind: 'chart', name: 'Chart', title: 'Two months',
        categories: { ref: 'C!$A$1:$B$1', values: ['Jan', 'Feb'] },
        series: [{ name: 'Series', ref: 'C!$A$2:$B$2', values: [10, 20] }],
        from: { col: 0, row: 3 }, to: { col: 6, row: 15 },
      }],
    }],
  }),
  docx: () => buildDocx({ paragraphs: ['hello & <world> é', ''] }),
  letter: () => buildLetterDocx({
    title: 'Balance confirmation',
    blocks: [{ text: 'Dear {{name}}' }, { tag: 'ar_balance', text: '0.00' }],
    pageNumbers: true,
  }),
};

/**
 * The pinned bytes.
 *
 * Established 2026-08-23 against the implementation as it moved out of
 * `erp-data-bindings`, which is the last point at which two independent
 * implementations existed to check against each other.
 */
const GOLDEN = {
  plain: '0efa90b8d264ab6c',
  styled: '85d5fca05731f3d0',
  multiSheet: 'cdd1ec2e7c941cea',
  formula: '69b54cd85783f45f',
  // Established 2026-08-24, when the creator learned to write a chart part.
  // Chart creation is strictly additive: every digest above it predates the
  // feature and none of them moved.
  charted: 'd894b0813e4cf4a3',
  docx: '943d649a35e3f76b',
  letter: 'bc53523d32dc9885',
};

for (const [name, build] of Object.entries(SHAPES)) {
  test(`${name}: the bytes are what they were`, () => {
    assert.equal(
      sha(build()), GOLDEN[name],
      `generated bytes changed for "${name}". If that was intended, update GOLDEN `
      + 'in the same commit and say what moved; if it was not, something in the '
      + 'creator or the package layer just changed a customer-facing file.',
    );
  });
}

test('building the same thing twice produces the same bytes', () => {
  // A creator that embedded the clock would make every content-addressed store
  // treat two identical documents as different ones — and Drive's blob store is
  // content-addressed, so this is the difference between deduplication working
  // and every save allocating fresh bytes.
  for (const [name, build] of Object.entries(SHAPES)) {
    assert.equal(sha(build()), sha(build()), `${name} is not deterministic`);
  }
});

test('values land where the spec put them, starting at A1', () => {
  // THE regression this file was written for. An off-by-one in the column
  // letters produces a workbook that opens perfectly and is wrong.
  const buf = buildXlsx({ sheets: [{ name: 'Data', rows: [['top-left', 'right'], ['below', null]] }] });
  const values = readSheetValues(buf);
  assert.equal(values[0][0], 'top-left', 'the first cell must be A1, not B1');
  assert.equal(values[0][1], 'right');
  assert.equal(values[1][0], 'below');

  const xml = OoxmlPackage.read(buf).text('xl/worksheets/sheet1.xml');
  assert.match(xml, /r="A1"/, 'the first cell reference must literally be A1');
  assert.ok(!/r="A2"[^>]*\/>\s*<c r="A2"/.test(xml), 'no duplicated references');
});

test('the column-letter helpers agree with each other and start at zero', () => {
  assert.equal(colName(0), 'A');
  assert.equal(colName(25), 'Z');
  assert.equal(colName(26), 'AA');
  assert.equal(cellRef(0, 0), 'A1');
  assert.equal(cellRef(9, 2), 'C10');
});

test('defined names and sheet names survive a round trip', () => {
  const buf = SHAPES.plain();
  assert.deepEqual(readSheetNames(buf), ['Data']);
  assert.deepEqual(readDefinedNames(buf), [{ name: 'Rng', ref: 'Data!$A$1:$B$2' }]);
});

test('XML entities survive being written and read back', () => {
  // Escaping that is not symmetrical corrupts exactly the values a person
  // notices: an ampersand in a customer name, an angle bracket in a note.
  const buf = buildXlsx({ sheets: [{ name: 'E', rows: [['a & b', '<tag>', '"quoted"', "it's", 'é']] }] });
  assert.deepEqual(readSheetValues(buf)[0], ['a & b', '<tag>', '"quoted"', "it's", 'é']);
});

test('a numeric character reference reads back as its character', () => {
  // The escaper that used to live in erp-data-bindings handled four entities;
  // the shared one also handles &apos; and &#nnn;. A cell holding &#233; used
  // to read back with the entity still in it.
  const buf = buildXlsx({ sheets: [{ name: 'N', rows: [['plain']] }] });
  const pkg = OoxmlPackage.read(buf);
  const xml = pkg.text('xl/worksheets/sheet1.xml').replace('plain', 'caf&#233;');
  pkg.write_('xl/worksheets/sheet1.xml', xml);
  assert.equal(readSheetValues(pkg.write())[0][0], 'café');
});

test('everything built here is a package the editor can open', () => {
  // The creator and the editor are two halves of one subject now. A file one
  // makes that the other cannot open would mean they had drifted apart again,
  // which is the whole thing the move was meant to prevent.
  for (const [name, build] of Object.entries(SHAPES)) {
    const pkg = OoxmlPackage.read(build());
    assert.ok(pkg.has('[Content_Types].xml'), `${name} has no content types`);
    assert.ok(pkg.has('_rels/.rels'), `${name} has no root relationships`);
    assert.ok(pkg.mainDocument(), `${name} declares no main document`);
  }
});

test('a workbook read back matches the spec it was built from', () => {
  const spec = { sheets: [{ name: 'Data', rows: [['a', 'b&<>"é'], ['1', '2']] }], definedNames: [{ name: 'Rng', ref: 'Data!$A$1:$B$2' }] };
  assert.deepEqual(readWorkbook(SHAPES.plain()), spec);
});
