// What the engines and the services say for a person to read — a file that
// will not open, a password refused, a step a document cannot take — marked
// for the catalogue, each written out as msg() needs it. The engines keep
// them in English (the main process, the tests and a log read them there);
// a window puts each into its own language as the message reaches it (the
// shell client's unwrap, messages.js tFilled), its {placeholders} filled back
// from the words the engine put there. No window imports this file: the
// catalogue's extractor reads it, and tests/catalogues.test.js holds each
// message to its translation in every catalogue. Made from the engines' own sources by listing what
// they throw; a message added there is added here the same way.

import { msg } from '@rutba/office-ui/messages';

export const ENGINE_WORDS = [
  // apps/desktop/main/calendar.js
  msg('The last calendar stays; delete its events instead.'),
  msg('This calendar comes from an account — remove the account to remove its calendars.'),
  msg('There is no invitation to answer.'),
  msg('That event is no longer there.'),
  // apps/desktop/main/dav-sync.js
  msg('No calendars or address books were found at that address.'),
  // apps/desktop/main/dav.js
  msg('A calendar or contacts server is reached over HTTPS — give its address with https://'),
  msg('The server did not accept the user name and password.'),
  msg('The server sent the request round in circles.'),
  msg('"{url}" is not a server address'),
  msg('The server answered {status} where a list was asked for.'),
  msg('The server refused to keep {href}: {status}'),
  msg('The server refused to remove {href}: {status}'),
  // apps/desktop/main/defaults.js
  msg('Windows keeps this choice for you: pick Rutba Office in Settings › Default apps. The button below opens it there.'),
  msg('macOS keeps this choice in Finder: select a file, press Command-I, choose Rutba Office under “Open with”, then Change All.'),
  msg('These are set with xdg-mime, which this can do directly.'),
  msg('Nothing could be set — the desktop entry may not be installed yet.'),
  msg('Settings is open. Choose Rutba Office there — Windows does not let a program set this for you.'),
  msg('macOS sets this in Finder: select a file, press Command-I, pick Rutba Office and choose Change All.'),
  msg('This platform is not supported yet.'),
  msg('{changed} file types now open with Rutba Office.'),
  // apps/desktop/main/doc-host.js
  msg('The document engine stopped, and the documents it held were closed. Unsaved work is kept as a recovery copy.'),
  msg('The document engine is starting again; try that once more.'),
  msg('The document engine is not running.'),
  msg('The document engine stopped while answering.'),
  msg('The main process cannot {fn} here.'),
  msg('That could not be sent to the document service: {v1}'),
  msg('The document service did not answer {name} in ten minutes.'),
  // apps/desktop/main/doc-worker.js
  msg('The answer to that could not be sent: {v1}'),
  msg('Rutba Office: the document service has no {name}.'),
  // apps/desktop/main/documents.js
  msg('A query reads a .csv, .tsv or .txt file'),
  msg('That document is no longer open.'),
  msg('Mail merge is a Word document\'s.'),
  msg('A new list needs a name to be saved under.'),
  msg('Only a scratch file of this suite is taken as a recording.'),
  msg('This document is protected: formatting is limited to styles.'),
  msg('Track Changes stays on: the document is protected for tracked changes.'),
  msg('Changes cannot be accepted or rejected while the document is protected for tracked changes.'),
  msg('This document is protected: only comments can be added here.'),
  msg('This document is protected for filling in forms: only its form fields can be changed.'),
  msg('This modification is not allowed because the selection is locked.'),
  msg('That recovered document is no longer there.'),
  msg('Only a document has a design to set as the default.'),
  msg('That is not an embedded document.'),
  msg('The embedded document is missing from the deck.'),
  msg('This document has never been saved, so it needs a name.'),
  msg('Equations here are for a presentation.'),
  msg('That equation cannot be built: {error}.'),
  msg('Rutba Office cannot open {v1} files yet.'),
  msg('The recipient list {path} is on a network share, so it is not opened from the letter. Choose it with Select Recipients → Use an Existing List.'),
  msg('The recipient list {path} was not found. Select Recipients to choose it again.'),
  // apps/desktop/main/mail-junk.js
  msg('"{address}" is not an address or a domain.'),
  // apps/desktop/main/mail.js
  msg('This build cannot sign in to that provider.'),
  msg('That account is not set up.'),
  msg('A sender goes on the Safe or the Blocked list.'),
  msg('That message was sent to you, not to a group or a mailing list — Never block sender keeps its sender instead.'),
  msg('No password is stored for {email}.'),
  msg('"{level}" is not a junk filter level.'),
  msg('"{bad}" is not an address or a domain.'),
  msg('"{bad}" is not a top-level domain, such as ru or cn.'),
  msg('"{bad}" is not an encoding the filter knows.'),
  // apps/desktop/main/main.js
  msg('No file was given to rename.'),
  msg('The name cannot contain a path separator.'),
  msg('That file no longer exists.'),
  msg('A file with that name already exists.'),
  msg('That file is open in a window. Close it first.'),
  // apps/desktop/main/oauth.js
  msg('That address is not one this can sign in to.'),
  msg('That account does not use a signed-in provider.'),
  msg('The sign-in came back with the wrong state, so it was refused.'),
  msg('The sign-in was not completed in five minutes. Nothing has been changed.'),
  msg('No {label} client id is set up in this build. See docs/OAUTH.md — it takes about five minutes and is free.'),
  // packages/doc-view/src/view.js
  msg('Sort works on the body\'s paragraphs; a table sorts by its own rows.'),
  msg('This selection crosses a table boundary — delete inside one cell at a time.'),
  msg('That password is not right, so the protection stays on.'),
  msg('Exceptions are set before protection is enforced — Stop Protection first.'),
  msg('Track Changes stays on: the document is protected for tracked changes. Stop Protection first.'),
  msg('A page break cannot start inside a table cell — move the caret out of the table.'),
  msg('Put the caret in a paragraph that starts with a letter'),
  msg('A picture cannot go inside a table cell yet — move the caret out of the table.'),
  msg('A signature line cannot go inside a table cell yet — move the caret out of the table.'),
  msg('An object cannot go inside a table cell yet — move the caret out of the table.'),
  msg('A diagram cannot go inside a table cell — move the caret out of the table.'),
  msg('A chart needs a table with a header row, a category column and at least one number.'),
  msg('No numbers found — a chart wants the table\'s body cells to be numeric.'),
  msg('The caret is not in a table.'),
  msg('Select from one cell to another in the same table, then merge.'),
  msg('This table has no column widths of its own to share out.'),
  msg('Draw the table at least a fifth of an inch wide.'),
  msg('Select recipients first — Mailings → Select Recipients.'),
  msg('No recipients are ticked in the list.'),
  // packages/imaging/src/gltf.js
  msg('This is not a binary glTF (.glb) file'),
  msg('The .glb file has no scene description'),
  msg('The model\'s buffer is missing'),
  msg('The model points at a buffer view it does not have'),
  msg('The model points at an accessor it does not have'),
  msg('This is not a glTF file: it is neither a .glb nor glTF\'s JSON'),
  msg('Only glTF 2.0 models are read'),
  msg('The model is compressed with Draco, which this suite does not decode'),
  msg('The model is compressed with meshopt, which this suite does not decode'),
  msg('The model has nothing to draw: no triangles in its scene'),
  msg('This is a glTF {version} file; only glTF 2.0 is read'),
  msg('The model needs the file "{uri}" beside it'),
  msg('The model stores numbers in a form ({componentType}) this does not read'),
  msg('The model needs the picture "{uri}" beside it'),
  // packages/office-formats/src/cfb-write.js
  msg('"{name}" cannot name a compound-file entry'),
  msg('"{v1}" is named twice'),
  // packages/office-formats/src/docx-read.js
  msg('Word document has no word/document.xml'),
  // packages/office-formats/src/odt.js
  msg('OpenDocument file has no content.xml'),
  // packages/office-shell/src/electron/ipc.js
  msg('Only a scratch file made in this run is added to.'),
  msg('That window has closed since the list was made.'),
  msg('Rutba Office: no backend for {ns}:{name}'),
  // packages/office-shell/src/electron/store.js
  msg('No OS keystore is available, so this password cannot be stored safely.'),
  // packages/ooxml/src/document.js
  msg('A formula here is numbers, cells like B2 or B2:B4, + - * / and brackets, and SUM, AVERAGE, COUNT, MAX, MIN, PRODUCT or ABS of them or of ABOVE, LEFT, BELOW or RIGHT — =SUM(ABOVE), say.'),
  msg('There is no sheet of labels in this document. Start Mail Merge → Labels makes one.'),
  msg('That 3D model\'s file is missing'),
  msg('A list needs at least one level.'),
  msg('A level\'s number text is too long.'),
  msg('A level starts at a whole number.'),
  msg('A style can be linked to one level only.'),
  msg('Only a text box has words to transform.'),
  msg('Bring Forward and Send Backward move floating drawings — choose a wrap other than In Line with Text first.'),
  msg('A text box goes beside the words, not in a table cell — move the caret out of the table first.'),
  msg('A text box cannot be anchored in this paragraph — it is part of a field or a content control.'),
  msg('Ink is anchored in a paragraph of the body.'),
  msg('A diagram goes in the body, after a paragraph of its own — move the caret out of the box or the table first.'),
  msg('Select two or more drawings to group them.'),
  msg('A drawing in line with the text cannot be grouped — give each one a wrap first (Layout → Wrap Text).'),
  msg('Only pictures, shapes, text boxes and groups can be grouped.'),
  msg('That drawing is not a group.'),
  msg('A watermark picture is a PNG, a JPEG, a GIF, a BMP or a WebP.'),
  msg('Something other than paragraphs sits inside the selection; select a plain run of paragraphs to sort.'),
  msg('This table has vertically merged cells — rows through a merge cannot be restructured yet.'),
  msg('This table has horizontally merged cells — its columns cannot be restructured yet.'),
  msg('There is no cell to the right to merge with.'),
  msg('These cells are part of a vertical merge — widening one row of it would tear the range.'),
  msg('Split a vertical merge from its first cell.'),
  msg('This cell is not merged — there is nothing to split.'),
  msg('A cell splits into 1 to 20 columns and 1 to 20 rows, more than one cell in all.'),
  msg('This table has no grid to split a cell in.'),
  msg('This cell is merged down its column — unmerge it before splitting it.'),
  msg('This cell runs past the table\'s grid, so it cannot be split.'),
  msg('That is the table\'s own edge — there is no cell beyond it to join.'),
  msg('The cells either side of that line are not the same width — make them match before rubbing it out.'),
  msg('A cell\'s line is its top, bottom, left or right.'),
  msg('Select across at least two cells to merge.'),
  msg('The selection already contains merged cells — split them first.'),
  msg('This table has cells merged down a column — split them before sorting its rows.'),
  msg('This table has something between its rows that sorting would lose.'),
  msg('The words to make a table of are in a table already.'),
  msg('Put the caret in the row the second table should start with — not the first.'),
  msg('A merge down a column crosses this row — split the merged cells first.'),
  msg('"{format}" is not a number style Word knows.'),
  msg('There is no paragraph style "{style}" to link a level to.'),
  // packages/ooxml/src/mailmerge.js
  msg('A bookmark needs a name that starts with a letter'),
  // packages/pdf/src/document.js
  msg('A PDF with no pages is not a document. Add a page first.'),
  msg('"{value}" is not a colour this can draw with.'),
  // packages/pdf/src/images.js
  msg('PNG colour type {colorType} is not supported'),
  msg('PNG filter {filter} is not in the specification'),
  // packages/pdf/src/sheet.js
  msg('A table needs columns.'),
  msg('A table row does not fit even on an empty page; the margins leave no body.'),
  // packages/presentation/src/deck.js
  msg('That is not a 3D model'),
  msg('That is not a Transform preset'),
  msg('A custom show needs a name.'),
  msg('An equation is edited in the equation editor — double-click it.'),
  msg('That shape has no words to transform'),
  msg('A table or chart frame has no fill or outline of its own.'),
  msg('A group has no fill or outline of its own — format a shape inside it.'),
  msg('Only a shape has points to edit.'),
  msg('A path starts with a point.'),
  msg('This comment was made in an older version of PowerPoint; it can be read and deleted, not replied to.'),
  msg('This comment was made in an older version of PowerPoint; it can be read and deleted, not resolved.'),
  msg('That design idea no longer fits this slide.'),
  msg('Clear formatting needs a shape with words.'),
  msg('A link needs a shape with words.'),
  msg('An action goes to a web address (http:// or https://) or an e-mail address (mailto:).'),
  msg('That slide has no cameo to record into'),
  msg('That is not a cameo'),
  msg('There is already a custom show called "{name}".'),
  // packages/presentation/src/motion.js
  msg('"{type}" is not a transition this writes'),
  // packages/presentation/src/timing.js
  msg('A motion path needs a path to follow'),
  msg('This slide\'s animations are laid out in a way this cannot rewrite; they are kept as they are.'),
  msg('Only an entrance, emphasis or exit this writes can be played by paragraph'),
  msg('The shape has no words to play paragraph by paragraph'),
  msg('"{name}" is not a motion path in the gallery'),
  msg('"{kind} {effect}" is not an animation this writes'),
  msg('"{effect}" is not an animation this writes'),
  // packages/sheet-view/src/advanced-filter.js
  msg('The criteria range needs its headings and at least one row of conditions under them'),
  msg('The list range needs a header row and at least one row under it'),
  msg('The criteria range needs its headings and at least one row of conditions — e.g. F1:G3'),
  msg('The criteria range cannot sit inside the list'),
  msg('Say where to copy the rows — a cell such as I1'),
  msg('The rows copied would land on the list or the criteria — choose a place beside or below them'),
  msg('No advanced filter is hiding rows on this sheet'),
  // packages/sheet-view/src/consolidate.js
  msg('Add at least one reference to consolidate.'),
  msg('Links cannot be created when the source and destination areas are on the same sheet.'),
  msg('This sheet is protected — unprotect it before consolidating into it.'),
  msg('The references hold nothing to consolidate.'),
  msg('Source references overlap destination area.'),
  // packages/sheet-view/src/forecast-sheet.js
  msg('A forecast is drawn as a line chart or a column chart.'),
  msg('The confidence interval is a percentage between 0 and 100.'),
  msg('Seasonality is detected automatically, or set to a whole number of points.'),
  msg('The timeline and the values are one column each.'),
  msg('The timeline and the values must be the same size.'),
  msg('Workbook is protected and cannot be changed.'),
  msg('The forecast end must come after the last point of the timeline.'),
  msg('The forecast end must be at least one step after the last point.'),
  // packages/sheet-view/src/outline.js
  msg('An outline goes seven levels deep at most'),
  msg('Auto Outline found no formula totalling the rows above it or the columns to its left, so there is nothing to outline.'),
  msg('This sheet has no outline to clear'),
  msg('Subtotal needs a list with a header row and at least one row of data under it'),
  msg('The column to group by is not in the list'),
  msg('Choose at least one column to add a subtotal to'),
  msg('There are no rows of data to subtotal'),
  msg('This list has no subtotals to remove'),
  // packages/sheet-view/src/queries.js
  msg('Append needs the other table'),
  msg('Merge needs the other table'),
  msg('A column needs a name'),
  msg('A conditional column needs a rule'),
  msg('A column is pivoted on another column\'s values'),
  msg('Pivot Column without adding up needs one value a cell; some rows share one'),
  msg('A column is split at something'),
  msg('Merge Columns needs two columns or more'),
  msg('Text is extracted before or after something'),
  msg('There is no column "{name}"'),
  msg('The other table has no column "{withOn}"'),
  msg('There is already a column "{to}"'),
  msg('"{type}" is not a type a column can be given'),
  msg('"{op}" is not a filter'),
  msg('"{op}" is not a condition'),
  msg('"{fn}" is not a way values are added up'),
  msg('"{fn}" is not a way rows are added up'),
  msg('"{how}" is not a change to text'),
  msg('"{how}" is not a way to extract text'),
  msg('"{kind}" is not a step a query takes'),
  // packages/sheet-view/src/query-load.js
  msg('A query needs a source'),
  msg('A file source is read on the main process'),
  msg('That query is no longer in this workbook'),
  msg('"{text}" is not a range'),
  msg('There is no query called "{v1}"'),
  msg('Query "{name}" reads itself'),
  msg('There is no table called "{table}"'),
  msg('There is no sheet called "{sheet}"'),
  msg('"{kind}" is not a source a query reads'),
  // packages/sheet-view/src/script-apply.js
  msg('This workbook is too large for a script to read at once'),
  msg('A script cannot set a cell outside the worksheet (A1 to XFD1048576)'),
  msg('A script cannot merge across part of a merged region'),
  msg('"{c}" is not a colour a script can set: a name or #RRGGBB'),
  msg('"{kind}" is not an edit a script makes'),
  // packages/sheet-view/src/scripts.js
  msg('That is more cells than a script may set at once'),
  msg('A script needs a function called main(workbook)'),
  msg('The script ran too long'),
  msg('"{address}" is not a cell or a range'),
  msg('There is no worksheet called "{name}"'),
  msg('"{to}" cannot be a worksheet\'s name here'),
  msg('There is already a worksheet called "{n}"'),
  // packages/sheet-view/src/view.js
  msg('This cell has a note. Delete the note, or edit it, before starting a comment here.'),
  msg('This cell has a comment. Reply to it, or delete it, before adding a note.'),
  msg('That range already has a table in it.'),
  msg('A workbook must contain at least one visible worksheet.'),
  msg('Paste Special pastes all, formulas, values or formats'),
  msg('Paste Special adds, subtracts, multiplies or divides'),
  msg('There is nothing copied to paste — copy some cells first'),
  msg('Cut cells are moved with Paste; Paste Special works on cells that were copied'),
  msg('Text to Columns takes one column at a time: select the cells of one column'),
  msg('Select a cell in a list or a table first: From Table/Range reads the data round it.'),
  msg('From Table/Range needs a row of headings and the data under it.'),
  msg('Flash Fill works beside a block of data — type an example in the column next to it'),
  msg('Type an example of what you want in this column first, then Flash Fill'),
  msg('Every row of the column is already filled'),
  msg('Flash Fill found no pattern that makes every example — type another example and try again'),
  msg('Flash Fill found the pattern but no other row has the parts it needs'),
  msg('Auto Fill Options change the fill just made — drag the fill handle first'),
  msg('A series is linear, growth, dates or AutoFill'),
  msg('A date series steps by a day, a weekday, a month or a year'),
  msg('The step value is a number'),
  msg('The stop value is a number'),
  msg('Select the cells to fill as well as the first one'),
  msg('Select the cells to fill, or give a stop value'),
  msg('That step never reaches the stop value: give another step, or select the cells to fill'),
  msg('A series starts from a number or a date in the first cell'),
  msg('Goal Seek needs a number to aim for'),
  msg('The cell to set must hold a formula — otherwise just type the value'),
  msg('The changing cell must hold a plain value, not a formula'),
  msg('That formula does not produce a number'),
  msg('Type the equation first.'),
  msg('That object is not an equation.'),
  msg('Type the words first.'),
  msg('Only a shape or a text box has words to transform.'),
  msg('Only a shape or a text box has words to change.'),
  msg('A scatter chart here plots up to three series — select a block of an X column and up to three Y columns.'),
  msg('Create from Selection needs a header row with at least one row of data under it'),
  msg('A pivot needs at least one field in Values.'),
  msg('Put the cursor in a pivot table first — or make one with Insert → PivotChart on the data.'),
  msg('Tick at least one field to make a slicer for.'),
  msg('A slicer keeps at least one item selected — Clear Filter shows them all.'),
  msg('Select a picture, shape, chart or slicer first.'),
  msg('Select two or more objects to align.'),
  msg('Select three or more objects to distribute.'),
  msg('Charts and slicers do not turn — select a picture, a shape or a group.'),
  msg('Select two or more objects to group.'),
  msg('A slicer is not grouped with other objects here — take it out of the selection.'),
  msg('Select a group to ungroup.'),
  msg('A name cannot be empty.'),
  msg('Say which cells the range covers, such as B2:D10.'),
  msg('A range needs a title.'),
  msg('A range title is letters, digits, spaces, dots, hyphens and underscores.'),
  msg('Select a cell with a formula in it, then Evaluate Formula steps through it.'),
  msg('A custom view needs a name.'),
  msg('A custom view name is 255 characters at most.'),
  msg('A background is a PNG, JPEG, GIF, BMP or WebP picture.'),
  msg('Select a cell inside your data first — a filter needs a range.'),
  msg('"{to}" is not a place Home or End goes to'),
];
