// The words the shared packages hand a window to show, marked for the
// catalogue, each written out as msg() needs it: an equation's name in
// Insert → Equation, a 3D model's views, the table styles, the themes and
// their colours, fonts and effects, WordArt's Transform presets, the pattern
// fills, bevels and 3-D rotations, the motion paths, a picture's details and
// the function categories, the citation styles and sources, the Table of
// Authorities categories, a field's descriptions, the envelope sizes and
// label kinds and the join kinds. The packages keep them in English (a document,
// the main process and the tests read them there); a window shows them
// through t() where it draws them, which finds them here. Nothing needs to
// import this file: the catalogue's extractor reads it. Made from the
// packages' own tables by listing their shown fields; a name added there is
// added here the same way.

import { msg } from '@rutba/office-ui';

export const SHARED_WORDS = [
  // Insert → Equation's gallery (@rutba/ooxml/math-linear)
  msg('Area of Circle'),
  msg('Binomial Theorem'),
  msg('Expansion of a Sum'),
  msg('Fourier Series'),
  msg('Pythagorean Theorem'),
  msg('Quadratic Formula'),
  msg('Taylor Expansion'),
  msg('Trig Identity 1'),
  msg('Trig Identity 2'),
  // 3D Model views (@rutba/imaging/model3d)
  msg('Front'),
  msg('Back'),
  msg('Left'),
  msg('Right'),
  msg('Top'),
  msg('Bottom'),
  msg('Above Front Left'),
  msg('Above Front Right'),
  msg('Below Front Left'),
  msg('Below Front Right'),
  // Table styles (@rutba/ooxml/table-styles)
  msg('Table Grid'),
  msg('Plain Table 1'),
  msg('Grid Table 1 Light'),
  msg('Grid Table 4'),
  msg('Grid Table 4 – Accent 1'),
  msg('Grid Table 4 – Accent 2'),
  msg('Grid Table 4 – Accent 3'),
  msg('Grid Table 4 – Accent 4'),
  msg('Grid Table 4 – Accent 5'),
  msg('Grid Table 4 – Accent 6'),
  msg('List Table 4'),
  msg('List Table 4 – Accent 1'),
  msg('List Table 4 – Accent 2'),
  msg('List Table 4 – Accent 3'),
  msg('List Table 4 – Accent 4'),
  msg('List Table 4 – Accent 5'),
  msg('List Table 4 – Accent 6'),
  // Themes (@rutba/office-formats/themes)
  msg('Rutba'),
  msg('Harbour'),
  msg('Meadow'),
  msg('Ember'),
  msg('Nightfall'),
  msg('Paper Kite'),
  msg('Basalt'),
  msg('Saffron'),
  msg('Tidewater'),
  msg('Orchard'),
  msg('Studio'),
  // Colour palettes
  msg('Rutba'),
  msg('Harbour'),
  msg('Meadow'),
  msg('Ember'),
  msg('Nightfall'),
  msg('Paper Kite'),
  msg('Basalt'),
  msg('Saffron'),
  msg('Tidewater'),
  msg('Orchard'),
  msg('Studio'),
  msg('Graphite'),
  msg('Lagoon'),
  msg('Citrus'),
  msg('Berry'),
  // Font pairs
  msg('Rutba'),
  msg('Classic'),
  msg('Editorial'),
  msg('Humanist'),
  msg('Friendly'),
  msg('Technical'),
  msg('Bookish'),
  msg('Grotesque'),
  msg('Newsprint'),
  msg('Plain'),
  msg('Readable'),
  // Effects
  msg('Flat'),
  msg('Solid fills, fine lines, no shadows'),
  msg('Soft'),
  msg('Gentle gradients and a soft shadow on intense shapes'),
  msg('Lifted'),
  msg('Rich gradients and shapes lifted off the slide'),
  msg('Outline'),
  msg('Flat fills with strong outlines'),
  // WordArt's Transform (@rutba/drawing/warp)
  msg('No Transform'),
  msg('Arch Up'),
  msg('Arch Down'),
  msg('Circle'),
  msg('Button'),
  msg('Triangle: Up'),
  msg('Triangle: Down'),
  msg('Chevron: Up'),
  msg('Chevron: Down'),
  msg('Curve: Up'),
  msg('Curve: Down'),
  msg('Wave: Down'),
  msg('Wave: Up'),
  msg('Double Wave: Down'),
  msg('Double Wave: Up'),
  msg('Inflate'),
  msg('Deflate'),
  msg('Inflate: Bottom'),
  msg('Deflate: Bottom'),
  msg('Inflate: Top'),
  msg('Deflate: Top'),
  msg('Fade: Right'),
  msg('Fade: Left'),
  msg('Slant: Up'),
  msg('Slant: Down'),
  msg('Square'),
  msg('Arch: Up'),
  msg('Arch: Down'),
  msg('Can: Up'),
  msg('Can: Down'),
  msg('Ring: Inside'),
  msg('Ring: Outside'),
  msg('Cascade: Up'),
  msg('Cascade: Down'),
  msg('Fade: Up'),
  msg('Fade: Down'),
  msg('Deflate-Inflate'),
  msg('Deflate-Inflate-Deflate'),
  msg('Stop'),
  msg('Circle (warp)'),
  msg('Button (warp)'),
  // Pattern fills (@rutba/presentation/patterns)
  msg('Horizontal'),
  msg('Vertical'),
  msg('Light horizontal'),
  msg('Light vertical'),
  msg('Dark horizontal'),
  msg('Dark vertical'),
  msg('Narrow horizontal'),
  msg('Narrow vertical'),
  msg('Dashed horizontal'),
  msg('Dashed vertical'),
  msg('Cross'),
  msg('Downward diagonal'),
  msg('Upward diagonal'),
  msg('Light downward diagonal'),
  msg('Light upward diagonal'),
  msg('Dark downward diagonal'),
  msg('Dark upward diagonal'),
  msg('Wide downward diagonal'),
  msg('Wide upward diagonal'),
  msg('Dashed downward diagonal'),
  msg('Dashed upward diagonal'),
  msg('Diagonal cross'),
  msg('Small checker board'),
  msg('Large checker board'),
  msg('Small grid'),
  msg('Large grid'),
  msg('Dotted grid'),
  msg('Small confetti'),
  msg('Large confetti'),
  msg('Horizontal brick'),
  msg('Diagonal brick'),
  msg('Solid diamond'),
  msg('Outlined diamond'),
  msg('Dotted diamond'),
  msg('Plaid'),
  msg('Sphere'),
  msg('Weave'),
  msg('Divot'),
  msg('Shingle'),
  msg('Wave'),
  msg('Trellis'),
  msg('Zig zag'),
  // Bevels and 3-D rotations (@rutba/presentation/shape3d)
  msg('Circle'),
  msg('Relaxed Inset'),
  msg('Cross'),
  msg('Cool Slant'),
  msg('Angle'),
  msg('Soft Round'),
  msg('Convex'),
  msg('Slope'),
  msg('Divot'),
  msg('Riblet'),
  msg('Hard Edge'),
  msg('Art Deco'),
  msg('No Rotation'),
  msg('Isometric: Left Down'),
  msg('Isometric: Right Up'),
  msg('Isometric: Top Up'),
  msg('Isometric: Bottom Down'),
  msg('Off Axis 1: Left'),
  msg('Off Axis 1: Right'),
  msg('Oblique: Top Left'),
  msg('Oblique: Top Right'),
  msg('Perspective: Front'),
  msg('Perspective: Left'),
  msg('Perspective: Right'),
  msg('Perspective: Above'),
  msg('Perspective: Below'),
  // Motion paths (@rutba/presentation/timing)
  msg('Down'),
  msg('Up'),
  msg('Left'),
  msg('Right'),
  msg('Arc Down'),
  msg('Arc Up'),
  msg('Turn Down'),
  msg('Turn Up'),
  msg('Circle'),
  msg('Square'),
  msg('Loop de Loop'),
  // A picture's details (@rutba/imaging/exif)
  msg('Camera'),
  msg('Lens'),
  msg('Exposure'),
  msg('Aperture'),
  msg('ISO'),
  msg('Focal length'),
  msg('Taken'),
  msg('Location'),
  msg('Software'),
  msg('Artist'),
  msg('Copyright'),
  msg('Orientation'),
  msg('as shot'),
  msg('mirrored'),
  msg('upside down'),
  msg('mirrored, upside down'),
  msg('mirrored, quarter turn'),
  msg('quarter turn clockwise'),
  msg('mirrored, three-quarter turn'),
  msg('quarter turn anticlockwise'),
  // Function categories (@rutba/formula)
  msg('Math & Trig'),
  msg('Statistical'),
  msg('Logical'),
  msg('Text'),
  msg('Lookup & Reference'),
  msg('Date & Time'),
  msg('Financial'),
  msg('Information'),
  // Citation styles and sources (@rutba/ooxml/bibliography)
  msg('Seventh Edition'),
  msg('Sixth Edition'),
  msg('Sixteenth Edition'),
  msg('Book'),
  msg('Book Section'),
  msg('Journal Article'),
  msg('Conference Proceedings'),
  msg('Report'),
  msg('Web site'),
  msg('Author'),
  msg('Title'),
  msg('Year'),
  msg('City'),
  msg('Publisher'),
  msg('Editor'),
  msg('Translator'),
  msg('Edition'),
  msg('Volume'),
  msg('Number of Volumes'),
  msg('Pages'),
  msg('Short Title'),
  msg('Standard Number'),
  msg('DOI'),
  msg('URL'),
  msg('Medium'),
  msg('Comments'),
  msg('Book Title'),
  msg('Book Author'),
  msg('Journal Name'),
  msg('Issue'),
  msg('Month'),
  msg('Day'),
  msg('Conference Name'),
  msg('Institution'),
  msg('Department'),
  msg('Report Type'),
  msg('Name of Web Page'),
  msg('Name of Web Site'),
  msg('Year Accessed'),
  msg('Month Accessed'),
  msg('Day Accessed'),
  msg('Production Company'),
  msg('Compiler'),
  msg('State/Province'),
  // Table of Authorities categories (@rutba/ooxml/wordtoa)
  msg('Cases'),
  msg('Statutes'),
  msg('Other Authorities'),
  msg('Rules'),
  msg('Treatises'),
  msg('Regulations'),
  msg('Constitutional Provisions'),
  // Field's descriptions and formats (@rutba/ooxml/docfields)
  msg('The name of the document\'s author, from its properties'),
  msg('Today\'s date'),
  msg('The document\'s file name'),
  msg('The number of pages in the document'),
  msg('The number of the page it is on'),
  msg('The time now'),
  msg('The document\'s title, from its properties'),
  msg('(none)'),
  msg('Uppercase'),
  msg('Lowercase'),
  msg('First capital'),
  msg('Title case'),
  // Envelope sizes and label kinds (@rutba/ooxml/labels)
  msg('DL — 110 × 220 mm'),
  msg('C5 — 162 × 229 mm'),
  msg('C6 — 114 × 162 mm'),
  msg('C4 — 229 × 324 mm'),
  msg('B5 — 176 × 250 mm'),
  msg('Size 10 — 4⅛ × 9½ in'),
  msg('Size 9 — 3⅞ × 8⅞ in'),
  msg('Monarch — 3⅞ × 7½ in'),
  msg('Size 6¾ — 3⅝ × 6½ in'),
  msg('Address'),
  msg('Parcel'),
  msg('Shipping'),
  msg('Multipurpose'),
  // Join kinds (@rutba/sheet-view/queries)
  msg('Left Outer (all from the first, matching from the second)'),
  msg('Inner (only matching rows)'),
  msg('Left Anti (rows only in the first)'),
  msg('Full Outer (all rows from both)'),
];
